---
title: "[Sprint 1] Sistema de Gestión de Pacientes (Base)"
labels: ["feature","core","high-priority"]
milestone: "Sprint 1: MVP Core - Infraestructura y Sistema Base"
assignees: ["Mauricio Sobarzo"]
---

# Sistema de Gestión de Pacientes (Base)

## Objetivo
Implementar el CRUD básico para gestión de pacientes y sus datos.

### Tareas
- [x] Crear modelo de paciente
- [x] Implementar endpoints CRUD
- [x] Añadir validación de datos
- [x] Implementar búsqueda de pacientes
- [x] Crear interfaz básica para gestión

### Criterios de Aceptación
- [x] CRUD completo de pacientes
- [x] Validación de datos del paciente
- [x] Búsqueda funcional
- [x] Interfaz operativa

_Sprint: Sprint 1: MVP Core - Infraestructura y Sistema Base_
_Fecha estimada: 5/5/2025_
_Completado: 20/7/2023_
