name: Error Check

on:
  schedule:
    - cron: '0 0 * * *'  # Runs at midnight every day
  workflow_dispatch:

jobs:
  check-errors:
    runs-on: ubuntu-latest
    name: Check TypeScript Errors
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18
          cache: 'npm'
      
      - name: Install dependencies
        run: npm ci
      
      - name: Check TypeScript errors
        id: ts-check
        run: |
          # Run type-check and save output
          npm run type-check > ts-output.log 2>&1 || true
          
          # Count total errors
          TOTAL_ERRORS=$(grep -c "error TS" ts-output.log || echo "0")
          echo "Total TypeScript errors: $TOTAL_ERRORS"
          
          # Count critical errors (e.g., syntax errors)
          CRITICAL_ERRORS=$(grep -c "error TS1" ts-output.log || echo "0")
          echo "Critical TypeScript errors: $CRITICAL_ERRORS"
          
          # Output for workflow
          echo "total=$TOTAL_ERRORS" >> $GITHUB_OUTPUT
          echo "critical=$CRITICAL_ERRORS" >> $GITHUB_OUTPUT
      
      - name: Create report
        run: |
          echo "# Error Report" > error-report.md
          echo "## TypeScript Errors" >> error-report.md
          echo "Total errors: ${{ steps.ts-check.outputs.total }}" >> error-report.md
          echo "Critical errors: ${{ steps.ts-check.outputs.critical }}" >> error-report.md
          
          if [ "${{ steps.ts-check.outputs.total }}" -gt "0" ]; then
            echo "### Error details" >> error-report.md
            echo '```' >> error-report.md
            head -n 50 ts-output.log >> error-report.md
            echo '```' >> error-report.md
          fi
      
      - name: Check if critical errors exist
        if: ${{ steps.ts-check.outputs.critical > 0 }}
        run: |
          echo "::warning::Found ${{ steps.ts-check.outputs.critical }} critical TypeScript errors that need immediate attention!"
