name: MVP Synchronization

on:
  workflow_dispatch:  # Permite ejecutar el workflow manualmente
  schedule:
    - cron: '0 0 * * 1'  # Se ejecuta cada lunes a las 00:00 UTC

jobs:
  sync-mvp:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          token: ${{ secrets.MAPLE_HEALTH_TOKEN }}
      
      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '18'
          
      - name: Install dependencies
        run: |
          npm install @octokit/rest dotenv
          
      - name: Generate MVP documentation
        run: |
          node scripts/exportMVPPlan.js
          
      - name: Generate local sprint files
        run: |
          node scripts/createLocalMVP.js
          
      - name: Sync with GitHub Projects
        env:
          GITHUB_TOKEN: ${{ secrets.MAPLE_HEALTH_TOKEN }}
        run: |
          node scripts/githubProjectIntegration.js
          
      - name: Commit documentation changes
        run: |
          git config --global user.name "GitHub Actions Bot"
          git config --global user.email "actions@github.com"
          git add mvp-plan.md mvp-plan.json docs/
          git commit -m "Actualizar documentación del MVP [skip ci]" || echo "No hay cambios para confirmar"
          git push