name: "Automatización Kanban"

on:
  issues:
    types: [opened, reopened, closed, labeled, unlabeled]
  pull_request:
    types: [opened, reopened, closed, review_requested]

permissions:
  issues: write
  pull-requests: write
  repository-projects: write

jobs:
  project_automation:
    runs-on: ubuntu-latest
    name: Automatizar Proyecto
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        
      - name: Actualizar Estado
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          ISSUE_URL: ${{ github.event.issue.html_url || github.event.pull_request.html_url }}
        run: |
          if [[ "${{ github.event_name }}" == "issues" || "${{ github.event_name }}" == "pull_request" ]]; then
            echo "Procesando ${{ github.event_name }} - ${{ github.event.action }}"
            
            if [[ "${{ github.event.action }}" == "opened" ]]; then
              echo "Nuevo item creado: $ISSUE_URL"
            elif [[ "${{ github.event.action }}" == "closed" ]]; then
              echo "Item cerrado: $ISSUE_URL"
            fi
          fi 