name: "Automatización de Proyecto"

on:
  issues:
    types: [opened, reopened, closed, labeled, unlabeled]
  pull_request:
    types: [opened, reopened, closed, review_requested]

permissions:
  issues: write
  pull-requests: write
  repository-projects: write

jobs:
  project_automation:
    runs-on: ubuntu-latest
    steps:
      - name: Update Issue Status
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          PROJECT_NUMBER: "1"
          ORGANIZATION: ${{ github.repository_owner }}
        run: |
          if [[ "${{ github.event_name }}" == "issues" || "${{ github.event_name }}" == "pull_request" ]]; then
            echo "Procesando ${{ github.event_name }} - ${{ github.event.action }}"
            
            # Obtener el ID del proyecto
            PROJECT_ID=$(curl -s -H "Authorization: Bearer $GH_TOKEN" \
              -H "Accept: application/vnd.github.v3+json" \
              "https://api.github.com/users/$ORGANIZATION/projects/$PROJECT_NUMBER" \
              | jq -r '.id')
            
            # Obtener el ID del issue o PR
            ITEM_ID="${{ github.event.issue.node_id || github.event.pull_request.node_id }}"
            
            if [[ ! -z "$ITEM_ID" ]]; then
              # Agregar el item al proyecto
              curl -X POST \
                -H "Authorization: Bearer $GH_TOKEN" \
                -H "Accept: application/vnd.github.v3+json" \
                "https://api.github.com/projects/$PROJECT_ID/cards" \
                -d "{\"content_id\":$ITEM_ID,\"content_type\":\"${github.event_name%s}\"}"
              
              echo "Item agregado al proyecto #$PROJECT_NUMBER"
            fi
          fi 